### ISSUE TITLE
Colab image issue

### ISSUE THREAD

**Issue by bsmith24** [Exabyte-io/api-examples#46]
![image_colab](https://user-images.githubusercontent.com/20477508/128780728-491fea90-9b23-495f-a091-11681150db37.jpeg)

**Comment by bsmith24** [comment]
![image_colab](https://user-images.githubusercontent.com/20477508/128782681-37597d59-f8a9-458d-9c94-926ffe3231e4.jpeg)

**Comment by mrakitin** [comment]
I don't observe this issue:

![image](https://github.com/Exabyte-io/api-examples/assets/13209176/ccef62f8-e486-49db-8716-b8eb06e69553)

I think it can be closed.
@timurbazhirov, what do you think?

**Comment by timurbazhirov** [comment]
This is fixed
